apiVersion: v1
kind: Service
metadata:
  name: procurement-portal-service
spec:
  type: LoadBalancer
  selector:
    app: procurement-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
